### ISSUE TITLE
Chutzpah VS 2015 tests are not always visible and not always executed if visible.

### ISSUE THREAD

**Issue by StephaneBischoff** [mmanela/chutzpah#439] opened 2015-12-21 23:07 UTC
Hi,

I am having a hard time getting Chutzpah to work correctly in Visual Studio Enterprise 2015.

I have a suite of QUnit tests. I have the Test Adapter and Test Runner version 4.1.0 installed via nuget.

For some reason, the Test Explorers does not show all the tests (it show some of them) although I have explicitly mentioned the paths within the Chutzpah.json file.

Furthermore, when I run the tests using run all, not all the tests are executed, just some of them.
If I go an explicitly run the tests that have not been executed, they run no problem.

I have no trace in the Output console, so I am not sure where to look anymore.

When I run the tests using the chutzpah.console.exe, I get a bit of random execution of tests. Sometime they run, sometimes not depending on the js unit test file. 

I have changed the parallelism to 1 in the options, but that did nothing.

Please help

**Comment by StephaneBischoff** [comment] 2015-12-22 13:16
Running the tests by opening them with the Chutzpah "Open in browser" menu works. A browser window opens and the tests are executed correctly in QUnit.

**Comment by mmanela** [comment] 2015-12-28 23:20
Can you produce a git repo that reproduces this issue. That way  I can run locally and test. But if not please give me the output of the /debug. As well you can run with /trace and provide me the chutzpah.log file.

**Comment by mmanela** [comment] 2016-08-24 06:13
Closing since no repro was given. Please re-open if still valid

**Closed by mmanela** 2016-08-24 06:13 UTC
