### ISSUE TITLE
Can't use the test window with chutzpah adapter

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#489] opened 2016-03-14 20:41 UTC
Hi,
I'm trying very hard to stay positive but it's hard... My current status is that I can no longer use the test explorer window as it does not do what it needs to be doing - I'm using the command line tool to run my test outside visual studio. the command I use is as follow:
```chutzpah.console.exe chutzpah.json```
Reasons: 
1. When trying to run only a set of tests I get the following message in the Tests window:
```------ Run test started ------
========== Run test finished: 0 run (0:00:01.5428325) ==========```
2. The total number of test I wrote and the number in the test window are not the same, as of writing these lines I have 43 tests when running from command line and only 31 in the test window:
![image](https://cloud.githubusercontent.com/assets/3269297/13759058/28b73aa2-ea35-11e5-94a2-3e50aa15a5fb.png)
![image](https://cloud.githubusercontent.com/assets/3269297/13759066/3a61b43a-ea35-11e5-81b0-096f8c87064a.png)
I'm sorry all I do is complain but I hope you can benefit from it and find bugs in order to improve your project which is very important and appreciated.

**Comment by HarelM** [comment] 2016-03-14 22:24
When running all the tests in VS I see the following error message which might explain why some tests results are missing:
Note that the following list has every member twice - if I look only at the unique entries the total number of test in the test explorer window and the list below sums up to 90 which is the correct number (C# test + ts tests, the number in my previous post was only ts tests).
```
------ Run test started ------
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should save to file'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should open from file'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should open from url'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize without any data'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize location data'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize markers from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be tolerant to points with single coordinate in search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a route from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a baselayer address from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a baselayer key from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should handle empty object in search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should inialize siteUrl from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be cleared when siteUrl is given'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be cleared when siteUrl is not given'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should update url with location'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should save to file'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should open from file'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'File Service Should open from url'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize without any data'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize location data'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize markers from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be tolerant to points with single coordinate in search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a route from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a baselayer address from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should initialize a baselayer key from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should handle empty object in search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should inialize siteUrl from search'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be cleared when siteUrl is given'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should be cleared when siteUrl is not given'.
Test adapter sent back a result for an unknown test case. Ignoring result for 'Hash Service Should update url with location'.
========== Run test finished: 75 run (0:00:19.804455) ==========
```

**Comment by mmanela** [comment] 2016-03-15 03:45
Sorry you are hitting issue. But I appreciate you taking the time to file them. It does help make the product better for you and everyone else.  

It sounds like you are reporting two issues. The first is that you cannot run a subset of the test files and I think that sounds like an existing bug in VS that should be fixed in update 2 coming out soon (https://github.com/mmanela/chutzpah/issues/474)

As for the count being wrong, can you give me a repro so I can try locally?

**Comment by HarelM** [comment] 2016-03-15 05:34
www.github.com/israelhikingmap/site

**Comment by mmanela** [comment] 2016-03-15 05:53
Thanks I can repro, it looks like some files are just not picked up (like HashServiceTests). I will debug why. In the mean while you can use the [Chutzpah Context Menu Extension](https://visualstudiogallery.msdn.microsoft.com/71a4e9bd-f660-448f-bd92-f5a65d39b7f0) to still be able to run from VS. This will work fine.

**Comment by mmanela** [comment] 2016-03-21 13:46
I root caused this issue to a bug in the Visual Studio test adapter framework. I am engaged with them on making the right long term solution but in the meanwhile I will look at a temporary fix for Chutzpah to mitigate this issue. Thanks for reporting and your patience while I fix.

**Comment by mmanela** [comment] 2016-03-28 00:14
I committed a change that seems to mitigate the issue on my box. It will still print lots of the duplicate warnings and errors to the console BUT it should correctly discover all the tests. Are you able to validate this change for me on your machine?

**Comment by HarelM** [comment] 2016-03-28 07:08
How would I got about doing that? Can you elaborate on the steps I need to do in order to test it?

**Comment by mmanela** [comment] 2016-04-05 22:19
I will release a new point release soon. Will let you know when and you can validate

**Comment by mmanela** [comment] 2016-04-05 23:18
Ok just published 4.2.1. You should still see the duplicate log output but I hope that it will now give you correct results in test exporer

**Comment by HarelM** [comment] 2016-04-06 22:32
Looks like all the tests are there, Thanks! Running "all" does as expected.
Running selected tests from the text explorer using "Shift" key to select tests results in the following error, and some tests do not run: 
```cs
Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test) in c:\Dev\chutzpah\VS2012.TestAdapter\ExecutionCallback.cs:line 47
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase) in c:\Dev\chutzpah\Chutzpah\Callbacks\ParallelRunnerCallbackAdapter.cs:line 55
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 329
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2() in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 58
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 68
   at Chutzpah.TestRunner.<>c__DisplayClass26.<InvokeTestRunner>b__23(ProcessStream processStream) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 542
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor) in c:\Dev\chutzpah\Chutzpah\ProcessHelper.cs:line 31
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 543
   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 356
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test) in c:\Dev\chutzpah\VS2012.TestAdapter\ExecutionCallback.cs:line 47
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase) in c:\Dev\chutzpah\Chutzpah\Callbacks\ParallelRunnerCallbackAdapter.cs:line 55
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 329
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2() in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 58
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by mmanela** [comment] 2016-04-07 15:21
That second error should be fixed with Visual Studio 2015 Update 2 (which I think was just released).

**Comment by HarelM** [comment] 2016-04-07 15:51
I've checked for updates yesterday, it wasn't there but I see it was released in MSDN, I'll see if I can update it and hopefully it will solve this. Thanks for the quick response and hard work!

**Comment by HarelM** [comment] 2016-04-08 13:49
Updated to update 2, I don't see any error messages. I think you can close this issue.
Thanks!

**Comment by mmanela** [comment] 2016-04-08 17:34
Awesome, thanks for your patience.

**Closed by mmanela** 2016-04-08 17:34 UTC
