### ISSUE TITLE
Jasmine tests not being recognized

### ISSUE THREAD

**Issue by rarawal** [mmanela/chutzpah#619] opened 2017-03-23 12:09 UTC
Hi,

Problem : 
1. Test explorer doesn't recognise Jasmine tests
2. Output when I right click in JS file is  : 0 passed, 0 failed, 0 total (chutzpah).

 My Chutzpah.json looks like below. My .sln file has 2 projects. 
Project 1-> Scripts -> ViewModel.js
Project 2-> Scripts -> TestViewModel.spec.js

I initially thought the issue is with paths so I actually gave constant path in the config file.

```
{
  "Framework": "jasmine",
  "References": [
    {
      "Path": "../Scripts/require.js"
    },
    {
      "Path": "../Application/ViewModel.js"
    }
  ],
   "Tests": [
    {
      "Include": "*/*spec.js",
      "Path": "Scripts"
    }
  ]
}
```

**Trace as below :**
chutzpah.console.exe Information: 0 : Time:14:36:34.7494381; Thread:1; Message:Building test context for ...\Scripts\ViewModel.js
chutzpah.console.exe Information: 0 : Time:14:36:34.7574594; Thread:1; Message:Excluding test files ...\Scripts\ViewModel.js given chutzpah.json settings
chutzpah.console.exe Warning: 0 : Time:14:36:34.7584622; Thread:1; Message:Unable to build test context for ...\Scripts\ViewModel.js
Message:Finished building test context for ...\Scripts\ViewModel.js
chutzpah.console.exe Information: 0 : Time:14:36:34.7654811; Thread:1; Message:Chutzpah run finished with 0 passed, 0 failed and 0 errors
chutzpah.console.exe Information: 0 : Time:14:36:34.7664836; Thread:1; Message:Chutzpah.json file cache cleared

Other JS files referenced in spec runner :
![image](https://cloud.githubusercontent.com/assets/18092687/24257530/6c399784-0feb-11e7-9262-50d99fe01190.png)

**Comment by rarawal** [comment] 2017-03-23 13:39
chutzpah.console.exe Information: 0 : Time:14:36:34.7494381; Thread:1; Message:Building test context for ...\Scripts\ViewModel.js
chutzpah.console.exe Information: 0 : Time:14:36:34.7574594; Thread:1; Message:Excluding test files ...\Scripts\ViewModel.js given chutzpah.json settings
chutzpah.console.exe Warning: 0 : Time:14:36:34.7584622; Thread:1; Message:Unable to build test context for ...\Scripts\ViewModel.js
Message:Finished building test context for  ...\Scripts\ViewModel.js
chutzpah.console.exe Information: 0 : Time:14:36:34.7654811; Thread:1; Message:Chutzpah run finished with 0 passed, 0 failed and 0 errors
chutzpah.console.exe Information: 0 : Time:14:36:34.7664836; Thread:1; Message:Chutzpah.json file cache cleared

**Comment by rarawal** [comment] 2017-03-23 16:05
![image](https://cloud.githubusercontent.com/assets/18092687/24257329/dfe9678c-0fea-11e7-8765-9d63bd985dec.png)

**Comment by deltreey** [comment] 2018-04-10 18:27
I can do this reliably with an existing project

```
> npx jasmine Functions\Tests.js
npx: installed 1 in 2.736s
Randomized with seed 85761
Started
........

9 specs, 0 failures
Finished in 0.02 seconds
Randomized with seed 85761 (jasmine --random=true --seed=85761)

> chutzpah.console /path Functions\Tests.js
Chutzpah console test runner  (64-bit .NET 4.0.30319.42000)
Version 4.3.6.0
Copyright (C) 2016 Matthew Manela (http://matthewmanela.com).


=== 0 total, 0 failed, took 0.12 seconds ===
```

**Comment by mmanela** [comment] 2018-04-10 21:30
Can you provide a simple repro I can clone and run?

**Comment by deltreey** [comment] 2018-04-10 21:38
yes.  I will provide that tomorrow.  First thing of note: source mapping in webpack causes this problem.  But there seem to be other things that cause it too.

**Comment by deltreey** [comment] 2018-04-11 19:17
@mmanela here you go https://github.com/deltreey/chutzhpah_jasmine_broken

**Comment by deltreey** [comment] 2018-04-13 20:15
updated the repo so the jasmine tests don't complain about the window object.  Specs fail, but the point is that they're present in Jasmine and not Chutzpah

**Comment by mmanela** [comment] 2018-04-15 14:06
At least in your sample, one big problem is that you are not compiling/transpiling for ES5. Chutzpah is using Phantom (for now) and it doesn't support any ES6 stuff.

**Comment by deltreey** [comment] 2018-04-16 18:18
es5 made a difference too.  With es5 configured, I was able to even have `source-map` turned on and not have issues.  To try and reproduce the broken project, I then swapped the `js` files to typescript, which broke things until I set typescript to output es5.  Then it began working in my sample project.  Now I'm trying to make other subtle changes to mimic the issue in my larger project again.

1. It looks like chutzpah still uses `chutzpah.json` even when it's not requested.  When I delete the `chutzpah.json` in my project, the tests are found and work as expected.  Basically, even though the command is `chutzpah.console <filename>` it is still using `chutzpah.json`, which is definitely not intended functionality
2. there still seem to be issues after I remove that caveat, (vs not picking up my tests, etc) but I will call them unrelated at this time.  Thanks, you can close this issue.

**Closed** 2018-09-28 14:53 UTC
Labels: wontfix
