### ISSUE TITLE
VS 2015 - Chutzpah dies, cannot recover

### ISSUE THREAD

**Issue by rposener** [mmanela/chutzpah#445] opened 2016-01-06 22:38 UTC
Runs great the first time, then re-running failed tests, cause this issue in VS 2015.  It cannot recover until restarting VS.  Does it every time we re-run a test.

Error: System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.COMException: The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test) in c:\Dev\chutzpah\VS2012.TestAdapter\ExecutionCallback.cs:line 47
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase) in c:\Dev\chutzpah\Chutzpah\Callbacks\ParallelRunnerCallbackAdapter.cs:line 55
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 331
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2() in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 60
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Chutzpah.TestCaseStreamReader.Read(ProcessStream processStream, TestOptions testOptions, TestContext testContext, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 70
   at Chutzpah.TestRunner.<>c__DisplayClass1d.<InvokeTestRunner>b__1a(ProcessStream processStream) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 494
   at Chutzpah.ProcessHelper.RunExecutableAndProcessOutput[T](String exePath, String arguments, Func`2 streamProcessor) in c:\Dev\chutzpah\Chutzpah\ProcessHelper.cs:line 30
   at Chutzpah.TestRunner.InvokeTestRunner(String headlessBrowserPath, TestOptions options, TestContext testContext, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 495
   at Chutzpah.TestRunner.<>c__DisplayClassc.<ExecuteTestContexts>b__b(TestContext testContext) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 308
---> (Inner Exception #0) System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context (mapping test id to test node).
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
   at Chutzpah.VS2012.TestAdapter.ExecutionCallback.TestStarted(TestCase test) in c:\Dev\chutzpah\VS2012.TestAdapter\ExecutionCallback.cs:line 47
   at Chutzpah.Callbacks.ParallelRunnerCallbackAdapter.TestStarted(TestCase testCase) in c:\Dev\chutzpah\Chutzpah\Callbacks\ParallelRunnerCallbackAdapter.cs:line 55
   at Chutzpah.TestCaseStreamReader.ReadFromStream(StreamReader stream, TestContext testContext, TestOptions testOptions, IList`1 streamingTestFileContexts, IList`1 deferredEvents, ITestMethodRunnerCallback callback, Boolean debugEnabled) in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 331
   at Chutzpah.TestCaseStreamReader.<>c__DisplayClass8.<Read>b__2() in c:\Dev\chutzpah\Chutzpah\TestCaseStreamReader.cs:line 60
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by rposener** [comment] 2016-01-06 22:39
Please let me know if there are other things I can do to help debug this.

**Comment by rposener** [comment] 2016-01-06 23:18
Here is my config: {
  "Framework": "qunit",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "TestFileAdjacent",
  "TypeScriptModuleKind": "AMD",
  "TypeScriptCodeGenTarget": "ES5",
  "References": [
    { "Path": "scripts/require.js" },
    { "Path": "config.js" },
    {
      "Path": "scripts/typings",
      "Includes": [ "*.d.ts" ],
      "IncludeInTestHarness": false
    }
  ],
  "Tests": [
    {
      "Includes": [ "*.test.ts" ]
    }
  ]
}

**Comment by rposener** [comment] 2016-01-07 16:31
Is there any chance you can provide a working sample which uses Typescript, AMD Modules, a custom require configuration for libraries, and does not use all that "compile" stuff?  Or do you have to use the compile.bat stuff that you have listed in your samples?  Seems silly when VS compiles the .ts files on save anyway.

**Comment by rposener** [comment] 2016-01-08 19:02
More update on this - the test adapter seems to fire twice every time.  Debug works now, but launches 2 windows,  and runs tests twice.  Also, it seems that the test discovery loses track of tests, and occasionally changing the name of the tests will trigger a rediscover, which corrects it but not always.  sometimes I have to restart VS to get the test list sorted out.  This is always accompanied by these messages in the output window, and only affect 1 file of tests - the other tests continue to appar and work: 

Test adapter sent back a result for an unknown test case. Ignoring result for '...'.

I have adapted the chutzpah.json file as follows to disable compilation:
{
  "Framework": "qunit",
  "EnableTestFileBatching": false,
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "TestFileAdjacent",
  "TypeScriptModuleKind": "AMD",
  "TypeScriptCodeGenTarget": "ES5",
  "Compile": {"Mode": "External"},
  "References": [
    { "Path": "scripts/require.js" },
    { "Path": "config.js" },
    {
      "Path": "scripts/typings",
      "Includes": [ "*.d.ts" ],
      "IncludeInTestHarness": false
    }
  ],
  "Tests": [
    {
      "Path": "modules",
      "Includes": [ "*.test.ts" ]
    }
  ]
}

**Comment by mmanela** [comment] 2016-01-11 17:30
Can you provide me a full repro?

Also, do you have VS 2015 Update 1 installed?

**Comment by rposener** [comment] 2016-01-28 17:04
Yes, I do have VS 2015 Update 1 installed - the details from ActivityLog.xml are: 
  <entry>
    <record>349</record>
    <time>2016/01/28 16:16:43.377</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [ChutzpahVS2012Package]</description>
    <guid>{A523D775-1341-4F21-A950-8C716E5628C9}</guid>
    <hr>80131500</hr>
    <errorinfo>Expected 1 export(s) with contract name "Chutzpah.VS2012.TestAdapter.IChutzpahSettingsMapper" but found 0 after applying applicable constraints.</errorinfo>
  </entry>

**Comment by mmanela** [comment] 2016-01-28 17:24
This looks like a dupe of #460 and where it was concluded that the [Productivity Power Tools 2015 for Visual Studio 2015](https://visualstudiogallery.msdn.microsoft.com/34ebc6a2-2777-421d-8914-e29c1dfa7f5d) seems to be doing something that is conflicting with Chutzpah and causing this issue. A question was posted on the [VS Extension site](https://visualstudiogallery.msdn.microsoft.com/34ebc6a2-2777-421d-8914-e29c1dfa7f5d/view/Discussions) but no response yet

**Comment by rposener** [comment] 2016-01-28 18:07
Thanks - I will have to stick with power tools and use a manual test harness for my js unit tests for now.  Please keep updated when there is a fix from either side.

**Comment by mmanela** [comment] 2016-01-28 18:22
You can use the other Chutzpah extension which should still work fine: https://visualstudiogallery.msdn.microsoft.com/71a4e9bd-f660-448f-bd92-f5a65d39b7f0

**Comment by mmanela** [comment] 2016-02-02 18:45
Closing this as dupe of #460, please use that bug to trace updates.

**Closed by mmanela** 2016-02-02 18:45 UTC
