### ISSUE TITLE
An exception occurred while invoking executor 'executor://chutzpah-js/': Unable to find headless browser: phantomjs.exe

### ISSUE THREAD

**Issue by akj627** [mmanela/chutzpah#402] opened 2015-09-15 12:47 UTC
We are getting this error on TFS.
An exception occurred while invoking executor 'executor://chutzpah-js/': Unable to find headless browser: phantomjs.exe See [http://go.microsoft.com/fwlink/?LinkId=254169] (http://go.microsoft.com/fwlink/?LinkId=254169). This error goes after we restart build controllers

**Comment by mmanela** [comment] 2015-09-15 16:18
I have never seen this issue. Do you have a repro or more information that can help reproduce the issue?

**Comment by akj627** [comment] 2015-12-22 16:24
Well, reproducing is hard as this error comes every 15-20 days and to fix it, we have to restart the build controller. I see that the error is coming from TestRunner.cs (line 163) https://github.com/mmanela/chutzpah/blob/master/Chutzpah/TestRunner.cs
Any ideas ?

**Comment by mmanela** [comment] 2016-01-23 20:46
Duplicate of #443

**Closed by mmanela** 2016-01-23 20:46 UTC
