### ISSUE TITLE
System.IO.IOException The process cannot access the file error at discovery phase.

### ISSUE THREAD

**Issue by SayusiAndo** [mmanela/chutzpah#387] opened 2015-08-19 18:56 UTC
Hi,

Thanks for this tool! It is awesome! However, something is not ok. I have checked the issues and nobody has reported something like this yet.

I'm using Visual Studio 2015 Enterprise with Chutzpah to test my javascript code. I get the error below continuously.

It does not matter whether the parallel is set up to 1 or 8. The error is the same.

As a consequence, obviously, the test explorer window does not list the tests described in that file.

I'm not using references in the spec files, they are in Chutzpah.json file.

Is there anything what is needed to figure out how to fix this?

Update: it works fine with references, but, the reason why I converted my project is that I don't want to copy-pasting the references...

```
------ Discover test started ------
Error: System.IO.IOException: The process cannot access the file '..path...\_Chutzpah.f96875093f45a5e0d78d2e58faf97799.test.html' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Chutzpah.Wrappers.FileSystemWrapper.Save(String path, String contents) in c:\Dev\chutzpah\Chutzpah\Wrappers\FileSystemWrapper.cs:line 172
   at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options) in c:\Dev\chutzpah\Chutzpah\TestHarnessBuilder.cs:line 74
   at Chutzpah.TestRunner.<>c__DisplayClassc.<ExecuteTestContexts>b__b(TestContext testContext) in c:\Dev\chutzpah\Chutzpah\TestRunner.cs:line 291
While Running:...path...\\oauthauthenticationdataservice.spec.js

Error: Error opening ...path.../_Chutzpah.f96875093f45a5e0d78d2e58faf97799.test.html: No such file or directory
While Running:...path...\oauthauthenticationdataservice.spec.js

Error: Unknown error occurred when executing test file. Received exit code of 2
While Running:...path...\oauthauthenticationdataservice.spec.js

========== Discover test finished: 0 found (0:00:01.3607047) ==========
```

I already created a question at [stackoverflow](http://stackoverflow.com/questions/32102686/chutzpah-exception-and-not-refreshing-test-list).

**Comment by mmanela** [comment] 2015-08-20 03:54
I have never seen this error before. Can you please create a repo that reproduces this issue and I can test locally

**Comment by SayusiAndo** [comment] 2015-08-20 18:14
Let me back to my machine which has the VS 2015 with .Net 4.5.2. I tried to reproduce on VS 2013 with .Net 4.5.0 but it works flawlessly. I'll provide a repository.

**Comment by SayusiAndo** [comment] 2015-08-21 16:50
Here [it](https://github.com/SayusiAndo/chutzpah.io.exception) is!

__How to reproduce the issue__:
* install both ([Test Runner Context Menu 4.0.3](https://visualstudiogallery.msdn.microsoft.com/71a4e9bd-f660-448f-bd92-f5a65d39b7f0), [Test Adapter for the Test Explorer 4.0.3](https://visualstudiogallery.msdn.microsoft.com/f8741f04-bae4-4900-81c7-7c9bfb9ed1fe))  plugin for VS 2015
* open the solution with VS 2015
* build the solution
* run all tests from Test Explorer --> all will be executed (2 fails, 12 passed)
* keep the Output window open
* select the requestAuthorizationService.Spec.js file and hit Enter somewhere in it and Save the file.

__Result__:
* you can see the exception

__Note__:
* if you repeat the steps above with VS 2013 then everything will be ok.

Let me know if you need anything else

**Comment by mmanela** [comment] 2015-08-23 15:01
Thanks, I was able to repro it once but then not consistently after. I will keep trying and see if I get it again and can narrow down why it happens

**Comment by mmanela** [comment] 2015-08-24 19:02
I was able to see it happen once but now I am unable to ever get it to repro. Does it happen consistently for you?

The error seems to indicate to me that somehow two threads are trying to run the same test file which should not happen.

**Comment by SayusiAndo** [comment] 2015-08-24 20:09
If you restart the VS it does not come up again?

How can I show you the setup what is needed for further debugging? Do you need memory dump? If so please describe me the steps and I'll do it.

It is consistent for me. Once I run the tests, it is going to throw this error, consistently.

I thought concurrent access can be the problem, but I changed the number of parallel processes in Chutzpah setup, but nothing happens.

**Comment by mmanela** [comment] 2015-08-27 00:59
Ok I see that issue. It looks like the VS test framework is calling Chutzpah __twice__ for the same file. This does not look right at all and I will dig deeper to see if it is something Chutzpah is doing or a bug in VS.

**Comment by SayusiAndo** [comment] 2015-08-29 11:23
Can it be related to that the tests are listed twice in the Test Explorer window?

**Comment by mmanela** [comment] 2015-08-29 14:24
Very possible. The weird thing is I had a repro going and then after a machine restart I once again can't repro. Very strange.

**Comment by SayusiAndo** [comment] 2015-08-30 12:37
I can reproduce it whenever I want. The top of that, since then my machine was reinstalled. Shall I create a video about it, or if you describe me how to do it then I can send you a memory dump.

**Comment by mmanela** [comment] 2015-08-31 17:06
Ok can you try something: Make a super simple test project with just one file called test.js with just one test in it. Using this project attempt to repro.

If that repros I can give you a build of Chutzpah that will cause a break point to be hit when it is in test discovery at which point you can take a process dump of the te.manageprocess process.

**Comment by mmanela** [comment] 2015-09-01 14:42
I am talking with the team that builds the VS adapter integration framework. They asked if setting the following registry flag resolves the issue. Can you try this out and let me know?

**Comment by SayusiAndo** [comment] 2015-09-01 14:43
Hi, sure. I can do it. I mean, either creating the project or setting the registry flag.

**Comment by mmanela** [comment] 2015-09-01 14:44
Try both :) and thanks.

**Comment by SayusiAndo** [comment] 2015-09-01 14:45
Ok :) , what is the registry flag?

**Comment by SayusiAndo** [comment] 2015-09-01 18:00
Changing the registry key helps. I cannot reproduce the error when it is set to '0'.

It is a fix for you or shall I create the small project and run the build you are going to provide me?

**Comment by mmanela** [comment] 2015-09-02 01:00
Ok that is interesting. I reported your results to the framework team. Please still do create a small project and test if you can repro in that (after clearing the registry change). If you repro there I will get you a new build.

**Comment by SayusiAndo** [comment] 2015-09-02 17:58
Ok. The small project is ready. The exception still comes.

**Comment by mmanela** [comment] 2015-09-03 14:18
Please go to here: http://1drv.ms/1LXdLtm
There is a file called Chutzpah.VS2012_BREAK.vsix

This will install the Chutzpah adapter but will force it to break before test discovery and test execution. Once you hit the first break point you can take a dump of the TE.ProcessHost.Managed.exe. You can do this by opening of task manager and looking for "Test Authoring and Execution Framework: TE.ProcessHost.Managed.exe". If you right click on that you will see a create dump option.

**Comment by SayusiAndo** [comment] 2015-09-04 22:25
Here is the dump:

http://1drv.ms/1JUGlt6

**Comment by mmanela** [comment] 2015-09-07 15:46
Thanks for the dump. Couple more questions:

1. Do you have Resharper installed? 
2. Can you list all the extensions you installed?

**Comment by SayusiAndo** [comment] 2015-09-07 16:56
No problem. Yes, I have resharper installed ( JetBrains ReSharper 9.0 Update 1 ).

I attached two screenshots about the installed packages, extensions:

![installedpackages1](https://cloud.githubusercontent.com/assets/5106373/9720766/e44849e8-5591-11e5-9eca-65b731841c18.PNG)
![installedpackages2](https://cloud.githubusercontent.com/assets/5106373/9720767/e680de0a-5591-11e5-8e42-a9f82a941500.PNG)

```
GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

JetBrains ReSharper Platform 6   Build 6.0.20141219.120158 on 2014-12-19 12:56:02Z
JetBrains ReSharper Platform package for Microsoft Visual Studio. For more information about ReSharper Platform, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

tangible T4 Editor   2.3.0
tangible engineering GmbH

TechTalk SpecFlow   2015.1
TechTalk SpecFlow - Binding business requirements to .NET code, http://www.specflow.org
Copyright © 2009–2013 TechTalk

Web Essentials 2015   0.5.170
Adds many useful features to Visual Studio for web developers.
```

**Comment by mmanela** [comment] 2015-09-07 18:03
Can you try disabling resharper and see if it repros?

**Comment by SayusiAndo** [comment] 2015-09-07 18:25
Hááhhhh! Without Resharper it works fine!

**Comment by mmanela** [comment] 2015-09-07 21:47
The team who works on the adapter framework says that resharper uses their infrastructure to build its own test runner. Apparently that somehow causes Chutzpah to get invoked twice from two separate threads when it should only be invoked once. 

Can you check if there is a way to just turn off resharper's test integration? If not, I will look into ways to work around it until the framework team can make a permanent fix.

**Comment by aleksandersmierciak** [comment] 2015-09-11 20:16
Hi,

I am encountering this issue as well and I do not have Resharper.

Most of the time, I get the error message identical to what @SayusiAndo has copied here; however, on rare occassions I am only given the stacktrace, the "no such file or directory" does not occur and I can see my unit tests in Test Explorer.

Tell me if you want that as a separate issue on GitHub. I will provide any additional information if needed as well.

**Comment by mmanela** [comment] 2015-09-15 16:23
@aleksandersmierciak Can you give some more information?

Please provide the logs for  devenv.exe and te.processhost.managed.exe when this issue occurs.
Please follow these steps to get logs..
1)	 Go to the path C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow and update the config file TE.ProcessHost.Managed.exe.config to TpTraceLevel =4; ( http://blogs.msdn.com/b/aseemb/archive/2012/03/02/how-to-enable-ute-logs.aspx )
2)	Go to the path C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE and update the config file devenv.exe.config file to TpTraceLevel =4; ( please follow the provided link to do so)
3)	Repro the scenario.
4)	Go to temp folder (%temp%) , there will be a text file of name te.processhost.managed.TpTrace and devenev.TpTrace.

**Comment by aleksandersmierciak** [comment] 2015-09-15 20:00
@mmanela I'd like to, but I cannot reproduce the issue anymore. The registry change was surprisingly reverted by itself and tests appear and execute anyway.

**Comment by ChrisMuis** [comment] 2015-11-14 21:08
@mmanela I have the same issues SayusiAndo. Only difference that I don't have Resharper installed. I have changed the reg key and that fixed it party. Except that I am still having duplicates of my tests in the Test Explorer.

**Comment by mmanela** [comment] 2015-11-16 18:14
@ChrisMuis Do you get the duplicated when you run from the command line also?

**Comment by rposener** [comment] 2015-12-30 05:55
I was having the same issue.  My project was a MVC4 project, and I had the Chutzpah Test Adapter and Chutzpah Test Runner Context Menu extensions installed.  I also have added the Chutzpah nugget package to my project.  On a hunch based on the comments here, I disabled the Chutzpah Test Runner and it appear to be working properly now.  I do see results twice, but do not see any error about the test.html file being in use.

My project is using typescript, and require/ amd to load the packages.  Here is the chutzpah.json file I am using - I wonder if this has something to do with them being run twice?

{
  "Framework": "qunit",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "TypeScriptModuleKind": "AMD",
  "TypeScriptCodeGenTarget": "ES5",
  "References": [
    { "Path": "scripts/require.js" },
    {
      "Path": "scripts",
      "Includes": [ "*.ts" ]
    },
    {
      "Path": "scripts/typings",
      "Includes": [ "*.d.ts" ],
      "IncludeInTestHarness": false
    }
  ],
  "Tests": [
    {
      "Includes": [ "*.ts" ],
      "Path": "specs"
    }
  ]
}

**Comment by mmanela** [comment] 2016-01-01 23:24
@rposener  Can you give me a full sample that I can run to see if I can repro?

**Comment by mmanela** [comment] 2016-01-23 20:51
@rposener ping

**Comment by Namstel** [comment] 2016-02-18 12:50
Hello @mmanela,

I too was receiving this error sporadically without using ReSharper. I found that removing Chutzpah Test Runner Context Menu Extension fixed it for me.

Is there anything you would like me to find out? Steps to take, logs to provide? I'd be happy to.

**Comment by mmanela** [comment] 2016-02-18 18:39
Wow, really. That surprised me since the context menu extension shouldn't interact with the adapter extension. Can you add it back and see if the issue returns?

**Comment by Namstel** [comment] 2016-02-19 07:56
You are correct. Adding it back didn't break it... perhaps it had something to do with restarting, even though other times restarting didn't do the trick. I'll keep an eye on it.

**Comment by mmanela** [comment] 2016-03-21 13:49
I root caused this issue to a bug in the Visual Studio test adapter framework. I am engaged with them on making the right long term solution but in the meanwhile I will look at a temporary fix for Chutzpah to mitigate this issue. Thanks for reporting and your patience while I fix.

**Comment by mmanela** [comment] 2016-03-21 13:49
Closing as a dupe of #489

**Closed** 2016-11-16 22:31 UTC
