### ISSUE TITLE
Cannot set working: VS2015 + TypeScript 1.3 + qunit OR Jasmine + Chutzpah

### ISSUE THREAD

**Issue by davidemannone** [mmanela/chutzpah#313] opened 2015-01-08 19:05 UTC
Dears, 

I'm using the configuration as in the title but I cannot set Chutzpah up to work even if I've rad and tried all'about I've found about using direcly compiled js files, compile with specifying tsc to use, and so on. I'm sure it's my fault but I can't find out the solution it may work for me and now I'm very confused. All the code seems to compile well and using only quint in another project and, without Chutzpah, sync and async tests works fine. 

My files are organized in this way: 

SolutionDir/cm/data/*.ts => all the classes I want to test are in the CM-project (there are also other folders other than data but for the moment I would be happy let it work for data) 

SolutionDir/cm/scipts/*.ts => support classes for all classes in data (only 2 classes are used and 2 .d.ts). 

SolutionDir/tests/unit/data/.ts => all the unit-tests classes are in a separate Tests-project, normally organized in 1 or more files thought to test 1 specific cm/data/xxx.ts file-class using 1 or more test() clause. Also here I have other ./unit/otherforders/.ts files that tests the same ./cm/data files or other files in ./cm/otherfolders. But I would be happy for now to let the ./data/* bring to work. 

SolutionDir/tests/unit/Facroty.ts => factory class I use within allmost all tests and is "referenced" within the test files. 

Premise: 
I've installed the "Chutzpah Test Runner Context Menu Extension" and what here reported comes from starting every time the same test file (with only 1 test() clause) by right click on them and select then "Chutzpah-ICON Run JS Tests" entry.
I've placed the Chutzpah.json file and/or the complile.bat file in SolutionDir/tests/unit/data.
Installing the "Chutzpah Test Adapter for the Test Explorer" the errors compares on the output windows under the voice "test" every time I compile all
Case 1: not using any Chutzpah.json file 
i got many of these: errors TS1056: Accessors are only available when targeting ECMAScript 5 and higher. 
I've verified and the errors refers to the use of getters and setters of TS. 

Case 2: using only ES5 flag: 
Chutzpah.json file: 
{
"TypeScriptCodeGenTarget": "ES5"
} 
and I got many of these: error TS1008: Unexpected token; 'constructor, function, accessor or variable' expected. 
I've verified and the errors refers to the use of "protected" accessor modifiers and so on of TS 1.3. 

Case 3: try to use external flag: 
Chutzpah.json file: 
{
"TypeScriptCodeGenTarget": "ES5",
"Compile": {
    "Mode": "External",
    "SourceDirectory": "../../../../CM/data"
}
} 
and I got only this unique error: 
Error: Called start() while already started (QUnit.config.semaphore was 0 already) 
While Running:C:\TFS\ChefMagic\dev-cm\Tests\Unit\data\Activity_tests.ts 

Case 3: try to use external flag and path settings: 
Chutzpah.json file: 
{
"TypeScriptCodeGenTarget": "ES5",
"Framework": "qunit",
"Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "SourceDirectory": "../../../../CM/data",
    "OutDirectory": "../../../../CM/data"
},
"Tests": [
    { "Include": "*.ts", "Exclude": "*.d.ts" }
],
"References": [
    { "Include": "../../../../CM/*/*.ts", "Exclude": "../../../../CM/*/*.d.ts" }
]
} 
and i get the same error as before: 
Error: Called start() while already started (QUnit.config.semaphore was 0 already) 
While Running:C:\TFS\ChefMagic\dev-cm\Tests\Unit\data\Activity_tests.ts 

Case 4: specify the tsc for compile: 
Chutzpah.json file: 
{
"TypeScriptCodeGenTarget": "ES5",
"Framework": "qunit",
"Compile": {
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "Executable": "compile.bat",
    "SourceDirectory": "../../../../CM/data",
    "OutDirectory": "../../../../CM/data"
},
"Tests": [
    { "Include": "*.ts", "Exclude": "*.d.ts" }
],
"References": [
    { "Include": "../../../../CM/data/*.ts", "Exclude": "../../../../CM/data/*.d.ts" }
]
} 
complie.bat file: 
@echo off 
tsc Activity_tests.ts --sourcemap 

and i got the same errors as before: TS1056 and TS1008 that relates to the use of ES5 and TS1.3 

Note: If I now remove the Chutzpah.json file at all I got this error: 
Chutzpah Error: ChutzpahCompilationFailedException - File not found 
While Running:C:\TFS\ChefMagic\dev-cm\Tests\Unit\data\chutzpah.json 

So, what's wrong with me? It's important to notice that VS2015 comes with TS allready installed but it seems not to work and so it was necessary to install TS1.3 for 2013 on top of VS2015 after it was ready and then all seems to work perfectly (compilation and quint tests without Chutzpah). 

Thank you in advance. 
Davide

**Comment by davidemannone** [comment] 2015-01-08 19:44
At the moment I've disabled Chutzpah plugin and started with new settings and tests based on Jasmine. Al works fine based on last TypeScript and also using the (maybe simpler) Jasmine Test Adapter plugin but that expects .jstest files to work. 

I've seen also that TypeScript has installed in my C:\Program Files (x86)\Microsoft SDKs\TypeScript\ 2 folders: 1.0 and 1.1 with each one a tsc.exe file.

**Comment by mmanela** [comment] 2015-01-18 18:07
Please create a small repro and upload to github. This is the best way for me to understand the issue and either advice you on the right changes or fix Chutzpah if there is a product bug.

**Comment by mmanela** [comment] 2015-01-23 20:12
I am not sure what issue you were having with TypeScript but Chutzpah should be playing no part in that. As long as either you compile before running Chutzpah or tell chutzpah a command to run to compile it should be fine. I was able to get your sample to work fine with the following chutzpah.json file:

    {
      "Compile": {
        "Mode": "External",
        "Extensions": [".ts"],
        "ExtensionsWithNoOutput": [".d.ts"]
       },
      "References": [
        { "Path": "TypeScript13Class.ts" }
      ],
      "Tests": [
        { "Path": "TypeScript13Class.test.ts" }
      ]
    }
    
    
I then ran

    chutzpah.console.exe .\Chutzpah\TypeScript13Class.test.ts
    
and it ran succesfully

**Comment by davidemannone** [comment] 2015-01-24 08:32
You’re right, it works fine, at least with the sample project, but surely with all of the rest. I've tried it out also with TS1.4 right now, and it's ok too.
 
The only difference I see is on the Path that here references a single file, wheras I tried to reference all of the files on a test directory. I tried out in this same example with References:Path:*.ts and the same in Tests:Path:*.ts or it would be better form me: Tests:Path:*.test.ts but it seems not to work again. With this setting file only the specified test files got to be listed on the text explorer!

So, could my fault be that? Shall I list all the single files instead and how I do that? It would be a bit boring, or not?

**Comment by mmanela** [comment] 2015-01-25 00:43
It will work if you use wild cards and include the files you need. Just remember they will all get put into one html file so you need to make sure you set up your references correctly. The best way to debug is to use the command line client and run /openwithbrowser. You can easily tell what is wrong in the browser and then adjust your settings

**Comment by davidemannone** [comment] 2015-01-25 01:54
For the example I sent you, how should that look for to make it work with all test files there? 
Ok for the html file for debug purpose, but you need it anyway even I use the test explorer to load/start the tests or the context menu, with the Chutzpah extension enabled?

**Comment by mmanela** [comment] 2015-01-25 04:10
Doing what I show below will work fine. You have some errors because of your js files being wrong but Chutzpah is correctly running them.

```
{
  "Compile": {
    "Mode": "External",
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"]
   },
  "References": [
    { "Include": "*.ts", "Exclude": "*.d.ts",  }
  ],
  "Tests": [
    { "Include": "*.test.ts", "Exclude": "*.tests.d.ts",  }
  ]
}
```

**Comment by davidemannone** [comment] 2015-02-04 01:04
Hy Mmanela and thank you for support.
I've done many test on my solution but I cannot still bring it to work for me. I don't think I've errors on the js files because I can start all tests fine with the provided qunit/jasmine html files and the standard browser starting from VS.
By using Chutzpah with test files placed in separate projects I cannot find the right way to instruct it via JSON where/how to find all the needed ts/js files by using SourceDirectory, OutDirectory, References and Tests properties. As soon as I need to reference files from out of the test project I get the "Can't find variable" output message. This belongs to missing js references when you start the tests but I cannot find out the right way to achieve the right combination that works for me.
I've download also the command line client as you suggested but I get always "0 totals" and no error messages. Maybe I'm doing also here something wrong or I don't have understood how to use it: I've simply opened a Windows Prompt Line window.

**Comment by mmanela** [comment] 2015-02-08 01:18
The key to debugging is when using the command line client doing two things.

1. Run it with the /openinbrowser flag and see what the generated HTML looks like to figure out what it is doing wrong.

2. Run it with the /trace flag which generates a chutzpah.log file which tells you everything that chutzpah did.

**Comment by davidemannone** [comment] 2015-02-08 01:35
Maybe I have missed to denote that we have many .js libraries we need to
specify to behave our tests to be executed and this libs are normally putted
in the "scripts" folder or in other subfolders of them. Let's say for
example jquery, angularjs, and so on. Normally the files inside them are
posted using the Nuget package manager. 

I think that I miss simply where to put this kind of information that, in a
simple html page, are expressed as single sequential "scripts lines".

 

I've never used the command line for the Chutzpah and I would try to use it
too, but don't know how to bring it to work. I look also on the guide, but
where should I write this command line? Should I configure in VS a new
"Chutzpah" external tool that runs on a separate command window? If yes,
what do I have to set then for them? Or is there something ready to use I
may use like opening the right the command window of VS?

**Comment by mmanela** [comment] 2015-02-08 06:47
The chutzpah command line .exe is just a regular windows command line executable. Put it somewhere in your path and you can just run

   chutzpah.console.exe /path TESTFILEPATH  /trace

or


   chutzpah.console.exe /path TESTFILEPATH  /openwithbrowser


from the console window.

**Comment by davidemannone** [comment] 2015-02-08 08:19
Ok, i did it:
1. I've downloaded the Chutzpah command line zip file
2. I've installed it
3. I made also some VS Tools commands that seems to work
4. I runned the commands you suggested from a win console, but this is the output I got by specify just one (ts) testfile

![image](https://cloud.githubusercontent.com/assets/7107478/6095873/f631db62-af72-11e4-9e24-50f7ae3a9e6e.png)

**Comment by davidemannone** [comment] 2015-02-08 14:17
Evaluating the log file I may get these results:

1. Message:Can't find location for generated path on C:\TFS\ChefMagic\dev\XShared\scripts\typings\jquery\jquery.d.ts since it is not inside of configured source dir C:\TFS\ChefMagic\dev\client
-> js files are not in the same location as the one described there because of:
1. we have a shared project for all d.ts (that contains also the same jss files as the projects to be tested) but the sourcedirectory prop of the json is a single string and i have choosen to point to che project where my files to test resides. If I would also change this then I will get the same problem for my target project. Couldn't it be possbile to make the sourcedirectory to be an array too?

2. Message:Couldn't find generated path for C:\TFS\ChefMagic\dev\client\app\scripts\filters\level.ts at C:\TFS\ChefMagic\dev\Client.Tests\app\scripts\filters\level.js
-> these file are missing because we have set the ts build option for generate a single output file. So it would find all of what neeeded if I could specifiy just this file, but again the sourcedirectory seems to be settable only with a single path and not with path+filename (other what concerns to the former point: it is a single string and not an array of paths/files)

Could these be the right outcomes? What could/should I do to overcome this problem using the Chutzpah.json setting file (or other else)?

**Comment by mmanela** [comment] 2015-02-08 16:21
Please show me the contents of your chutzpah.json file?

However, you do point out two limitations in chutzpah currently.

1. In the compilation settings it is limited to one source and one out directory that are expected to match in layout. The idea here is that usually you will invoke your compiler like this (tsc c:\my\project\src) and expect the output to either be inline or in a parallel folder structure (c:\my\project\out). I have heard of some cases where this is not 100% accurate since people can have complicated layout structures. I plan to investigate extending this so you can specify multiple directories and chutzpah will try to find the best match


2. You are 100% correct that Chutzpah does not work well right now if you are running on source .ts files but you compile your output to one big .js file. This is a gap in Chutzpah and I plan to address. This would require a decent amount of change since Chutzpah has always assume a 1x1 correspondence

I would still like to see you .json file but I think it may be that without new features from Chutzpah you won't get it to work perfectly.

**Comment by davidemannone** [comment] 2015-02-08 18:29
This is the json that produced the former log output:
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ],
		"SourceDirectory": "../client"
	},
	"References": [
		{ "Include": "_references.ts", "Exclude": "*.d.ts" }
	],
	"Tests": [
		{ "Include": "*/other/*.ts", "Exclude": "*/other/*.d.ts" },
		{ "Include": "*/filters/*.ts", "Exclude": "*/filters/*.d.ts" }
	]
}

What concerns your answer I think we could have now addressed the problem.

1. I'm not sure how to match my needs with your explanation, but a simple request/feature that I could understand is: it should be possible to specify/inject any needed js file that is necessary for a test and not only whom are typescripted. We have also to admit that not all js sw has already been typed and moreover in the feature they will still be made later than the latest updated js libs available. 
But this is today simply achieved by using testing js frameworks with html output or even phantomjs. 

2. This could be simply solved in VS by defining a specific build environment that by tests do not makes the single file. But it will/could still not work if the 1 is not fixed.

I like very much your VS plug-in and you have done a great well working sw, when used, it seems, for standalone projects. I hope you could propose a solution for fix that very soon.  

Thank you very much Mmanela for all the great work and support!

**Comment by mmanela** [comment] 2015-02-08 21:57
1. You can list any .js file in your references section. If you know where it is just list it  
```
"References": [
{ "Include": "_references.ts", "Exclude": ".d.ts" },
{ "Include": "*/some/folder/*.js" }
],
```
I am not sure if that helps you but you can try.

2.

**Comment by davidemannone** [comment] 2015-02-09 02:07
I give you my first feedback.
With this json:
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ]
	},
	"References": [
		{ "Include": "*.js" },
		{ "Include": "_references.ts", "Exclude": "*.d.ts" }
	],
	"Tests": [
		{ "Include": "*/other/*.ts", "Exclude": "*/other/*.d.ts" },
		{ "Include": "*/filters/*.ts", "Exclude": "*/filters/*.d.ts" }
	]
}

the first group of tests now executes and passes! What I had to do more to let it work is to add also a move/copy post build event that moves the single generated ts-output file to the root dir of the test-project.

This was necessary because it seems not to work something like this:
	"References": [
		{ "Include": "../myproject/*.js" },
or this:
	"References": [
		{ "Include": "*/../myproject/*.js" },
or this:
	"References": [
		{ "Include": "*../myproject/*.js" },
but also not specifying the full path like this:
	"References": [
		{ "Include": "c:/mysolution/myproject/*.js" },


and nor scpecifying a single file such this:
	"References": [
		{ "Include": "myfile.js" },

and also not:
	"References": [
		{ "Include": "../myproject/myfile.js" },
or that:
	"References": [
		{ "Include": "c:/mysolution/myproject/myfile.js" },

(note: myproject is a generic NON-test project that I need to reference from the corresponding test project where the Chutzpah.json file resides)

It seemed not possibile go back ".." and also not use an absolute path, nor specify a single named.js file. Could it be right? Or should it be possibile to achieve something like this? Consider that I've overcomed that by moving files (just one thanks to ts build options) through projects. This operation is not difficult to do but it makes necessary to write some extra commands in the project settings and force always a project rebuild process to take this move/copy to take place (the save and compile isn't enough now). So, I think it would be still a good thing to allow relative, absolute and single file references to work properly. 
Maybe bring to work properly just only this wouldn't be such a difficult feature, or I hope so, so to have just this fix very soon.

Now I have to discover what happens when more target-projects are referenced from one test-project!

**Comment by davidemannone** [comment] 2015-02-09 02:43
I have right another problem now:
In a test project I have some factories classes/files all inside a factory folder that are referenced from some test.ts files of the same test project. I get again "undefined" errors in the test files that derives from these factories classes. I'm still using the _references.ts files to address the right "references" order between .ts files by the tsc. 

I tryied out this:
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ]
	},
	"References": [
		{ "Include": "*.js" },
		{ "Include": "_references.ts", "Exclude": "*.d.ts" },
		{ "Include": "*/factories/*.ts", "Exclude": "*/factories/*.d.ts" },
	],
	"Tests": [
		{ "Include": "*/model/*.ts", "Exclude": "*/model/*.d.ts" }
	]
}

or this:
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ]
	},
	"References": [
		{ "Include": "*.js" },
		{ "Include": "_references.ts", "Exclude": "*.d.ts" }
	],
	"Tests": [
		{ "Include": "*/other/*.ts", "Exclude": "*/other/*.d.ts" },
		{ "Include": "*/factories/*.ts", "Exclude": "*/factories/*.d.ts" },
		{ "Include": "*/model/*.ts", "Exclude": "*/model/*.d.ts" }
	]
}

**Comment by davidemannone** [comment] 2015-02-09 07:26
Going further with my test I've got another "undefined" message and this is the log:

chutzpah.console.exe Information: 0 : Time:03:59:13.4078846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/app.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4078846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/cm.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4078846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/cm.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4078846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/_references.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4178846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/_references.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4178846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Factories/modelfactory.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4178846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Factories/modelfactory.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4278846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Model/Activity.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4278846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Model/Activity.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4278846; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Other/qunitTest.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4388847; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Other/qunitTest.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4398847; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jshashtable_src.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4398847; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jshashtable_src.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4398847; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/factories/modelfactory.js
chutzpah.console.exe Information: 0 : Time:03:59:13.4498847; Thread:4; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/factories/modelfactory.js
....
chutzpah.console.exe Error: 0 : Time:03:59:13.4798848; Thread:4; Message:Eror recieved from Phantom ReferenceError: Can't find variable: Hashtable
....

What I notice are two things:
1. The files in /scripts seemed to be loaded by default or at least I have done nothing for this to happens. And this is good! But I'm wondering why they are loaded as last? If a definition is used by my test files or else, couldn't it be that this is then missing? I'm not sure yet of this is right the case now but I'm used to put the scripts files always before the tests/MyOwn files when I make the test-index file.

2. Why are all files listed/loaded twice?

**Comment by mmanela** [comment] 2015-02-12 14:34
The "Include" parameters are pattern matching (usually you start with with a wildcard *). If you want more control you should combine them with the path parameter. Like

    { "Path" "../../", "Include": "*/foo/hello.js" }


I don't follow your other questions totally. Could you give me a repro with a readme.txt that is describing what I am looking for.

**Comment by davidemannone** [comment] 2015-02-12 15:51
Thank you Mmanela
I have to figure out how to use it, but I will try it soon. Do you think I wiil resolve so the duplicated items error?
Please let me try to summarize before making other example projects to send you. By looking to your generated log file I have seen this:
1. You inject the js source files to PhantomJs as the last in order instead of be the first of all injections. This may be a wrong approach and should be fixed.
2. I assume that by using the workaround of the {include: "*.js"} you ends to add every file twice. Could this be? Maybe your former solution is thought to avoid exactly this problem?

**Comment by mmanela** [comment] 2015-02-12 17:08
The files should be injected into the HTML file in the order you list in the references file. Are you talked about if you do *.js the order it finds them in the file system?

**Comment by mmanela** [comment] 2015-02-13 04:31
So again, please give me a full repro. But looking at what you have

1. { "Include": ".js" }, should be { "Include": "*.js" },

And that is in general, you should put the wildcard in front of the include excludes.

**Comment by davidemannone** [comment] 2015-02-13 10:16
Hello,
ok that's wrong! I'm so sorry: all * are right there, but when I publish the response they are removed!

{
"Compile": {
"Mode": "External",
"Extensions": [ ".ts" ],
"ExtensionsWithNoOutput": [ ".d.ts" ]
},
"References": [
{ "Include": "STAR.js" },
{ "Include": "_references.ts", "Exclude": "STAR.d.ts" }
],
"Tests": [
{ "Include": "STAR/other/.ts", "Exclude": "STAR/other/.d.ts" },
{ "Include": "STAR/filters/.ts", "Exclude": "STAR/filters/.d.ts" }
]
}

Anyway, the problem of the order you use in injecting the code, seems to me, not to be affected by such a problem (if it would also exist) and I have listed in this post (and tagged extensively) what parts of your log seems to me to be placed in a worng place:
The error reported comes form an undefined variabile that would exists if the script-files would be injected befor my own code.
 I've sent you also the whole log file for inspection...

**Comment by mmanela** [comment] 2015-02-14 16:36
If you want those files placed first why not just reference them at the top of your chutzpah.json file references section?

**Comment by davidemannone** [comment] 2015-02-14 17:14
But how can I reference them if they are files placed in the "sprits" folder? You did all from yourself.
JQuery or whatever else, are common libs placed in the scripts folder and I do not specified them explicetely anywhere or even I did it in some indirect way (by _references files or <reference path> in d.files) they are always the first declarations you may encounter during file search process.
Moreower: you may include all that is found on the scripts folder and it seems to me you did it, because not all used libs are definitelytyped!

**Comment by davidemannone** [comment] 2015-02-14 17:35
But did you looked the log file you've generated and I posted here?
I will report i here again and this time place my comments on the original output (removing only the duplicated lines)

******************************* THIS SHOULD COME FROM THE: "references", "include": "STAR.js"
chutzpah.console.exe Information: 0 : Time:02:27:24.7591216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/cm.js

******************************* THIS SHOULD COME FROM A: "references", "include": "_references.ts"
chutzpah.console.exe Information: 0 : Time:02:27:24.7591216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/_references.js

******************************* THIS SHOULD BE DETERMINED BY YOU DIRECTLY BY SOME FOUND REFERENCES
chutzpah.console.exe Information: 0 : Time:02:27:24.7591216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Factories/modelfactory.js

******************************* THIS SHOULD COME FROM A: "test", "include": "STAR\model\START.js"
chutzpah.console.exe Information: 0 : Time:02:27:24.7691216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Model/Activity.js

******************************* THIS SHOULD COME FROM A: "test", "include": "STAR\other\START.js"
chutzpah.console.exe Information: 0 : Time:02:27:24.7691216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Other/qunitTest.js

******************************* WHY DO YOU PLACE ALL SCRIPTS FILES ONLY FOR NOW ONE?
******************************* THEY SHOULD BE PLACED ON TOP OF THIS LIST!
******************************* AND I DO NOT HAVE WRITTEN ANYTHING OF THEM ON YOUR .JSON FILE NOR THEY ARE REFERENCED ANYWAY BY D.TS FILES: YOU HAVE IMPORTED ALL OF WHAT YOU'VE FOUND IN THE SCRIPTS FOLDER OR I CAN CONFIRM YOU DID IT IN THIS CASE BECAUSE THIS ARE ALL OF THE FILES NUGET HAS PLACED FOR ME THERE. BY LOADING ALL WHAT IS FOUND IS MADE RIGHT BY YOU, BUT YOU SHOULD INJECT THE FILES AS FIRST OF ALL THINGS, NOT AS LAST.
chutzpah.console.exe Information: 0 : Time:02:27:24.7791216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jquery-2.1.3.intellisense.js
chutzpah.console.exe Information: 0 : Time:02:27:24.7791216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jquery-2.1.3.js
chutzpah.console.exe Information: 0 : Time:02:27:24.7991216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jquery-2.1.3.min.js
chutzpah.console.exe Information: 0 : Time:02:27:24.8191216; Thread:5; Message:Phantom Log - Resource Recieved: file:///C:/TFS/ChefMagic/dev/CM.Tests/Scripts/jshashtable.js

**Comment by mmanela** [comment] 2015-02-14 22:32
Once again, please give me a full zip file containing the repro of you issue so I can run locally.

**Comment by mmanela** [comment] 2015-02-15 15:31
After looking at the sample you gave me through email I suggest making this your chutzpah.json. The issue is that  when you do *.js, it would match ALL .js files even the ones nested in folder. The way the order file system finds those files can be hard to know which is why the order in your HTML was wrong.


```
{
	"Compile": {
		"Mode": "External",
		"Extensions": [ ".ts" ],
		"ExtensionsWithNoOutput": [ ".d.ts" ]
	},
	"References": [
		{ "Path": "Scripts/jquery-2.1.3.js" },
		{ "Path": "Scripts/AnyOtherNoTSFileChutzpahWillAddCorrectlyAnyway.js" },
		{ "Include": "*.ts", "Exclude": "*.d.ts"  }
	],
	"Tests": [
		{ "Include": "*.ts", "Exclude": "*.d.ts" }
	]
}
```

**Comment by davidemannone** [comment] 2015-02-15 16:44
Hy Matthew: I feel I will soon reach a stable result using Chutzpah.

The example would not work do to the fact that the last "References"-"Include" line should be STAR.js instead of STAR.ts and this because, in the real problem we outlined, it was the workaround proposed by you for overcome the project cross test file references and then the tsc-make-single-file-output (both known problem of Chutzpah until now).

Anyway, what you say is to reference for my own, by using "Path" in "References", all of the files that are needed. This means 2 main things:
1. I can reference any js-file that is a non-ts-file
2. I can reference directly the COPY/XCOPY files instead of using the wildcards
In this way it looks like to be the same as I would build for my own the html file and this is good (at least it is so for my situation).

I updated my json, made a test and finally it seemed to produce a "passed" test result. I will now extend this solution to all of my projects and I will get an (surely ok) overall result.

For now thank you very much for all the help and... all of your work with Chutzpah.

**Comment by mmanela** [comment] 2015-02-15 22:33
Yes, you came to a key understanding that at the worst case you can tell Chutzpah __exactly__ what files you want it to use and it should listen to you :)

**Comment by davidemannone** [comment] 2015-02-16 05:57
It seems to work exactly as you said. You made a very good work with Chutzpah and in this way it is possibile to do everything without having any other issue such ad msbuild, batch, and so on. With few json lines all of the "compile" work is done by the VS environment (I'm using right now TS1.4) and whatever the solution looks like I can address the files simply by drag&drop them where they should appear.
Maybe it is a little bit less automated as you might have thought for Chutzpah but having control on what should happens exactly should be appraciated by every programmer.
Looking now from where I was starting with all the text, projects and logs I wrote you, it seems to me you have comprised deeply this new possibility right now too. That's lucky!

Sprry for now but, I will ask you this now: 
I've rad what you wrote about Chutzpah, you have introduced json's feature for overcome updating process regard to specific build actions and TS versions. And I was using it because it was exactly my case, but what about the test framwork? By looking deepliy on your logs i'm wondering how is it handled? From where do you get the test-framework-js-files and what happens if the test framework will update faster than you ever will update Chutzpah? And more: how can I specify also which of these files to use, that means implicetly also this: how con I setup another test framework you have not thought to before (not one of qunit, jasime or mocha). 
With the above conclusion we reached here, it seems to me possibile to tune also this aspect by just specifying also the test framework files I intend to use right on the top of the json, but I'm not sure it will finaly work as expected do to output integration such as diplay the results in the VS test window.

**Comment by mmanela** [comment] 2015-02-16 06:10
Thanks for the kind words David. Chutzpah originally took the view of it will do everything for you and over the years I have worked to make it more flexible since everyone's setup is unique.

That said you are hitting on one of the main pieces where Chutzpah is not as flexible: test framework. Chutzpah owns the version of the test framework it uses and needs special code in order to integrate with them. This is why I don't let you customize the version of Qunit,Jasmine or Mocha. If you did that there is a good chance something might not work (especially when one of those frameworks have a major changes). 

As for adding a new framework, this is possible but not without code changes to Chutzpah.

**Comment by davidemannone** [comment] 2015-02-16 14:59
Right... so there is work for you! ;)
I've discovered right now by setup all with this settings, that very few tests did not pass anyway and I have to investigate why: with the test html page all works fine.
And what about async test? I have some that runs for more than 10s and it seems to me not to be displayed anywhere. Is it possible?

**Comment by mmanela** [comment] 2015-02-16 15:50
Async tests are supported but Chutzpah may throw a timeout if they take too long unless you extend its timeout setting.

**Comment by mmanela** [comment] 2015-08-24 15:12
Closing issue. Original poster can re-open if not fixed.

**Closed by mmanela** 2015-08-24 15:12 UTC
