### ISSUE TITLE
Chutzpah console says there are no expectations, but there are expectations

### ISSUE THREAD

**Issue by dpmartin990** [mmanela/chutzpah#581] opened 2016-12-12 21:13 UTC
So locally in VS this test passes.  When I run through chutzpah console, it says there are no expectations.  I have tried both these variants below, and the inconsistency is the same either way.  There are clearly expectations, so I'm mystified as to what is going on.  Your assistance is appreciated, let me know if you need more detail.

```
~~~~~
it('should assign appid and environment details to provider',
    function () {
        var appId = 9086;
        var enviroment = 'DEV';
        expect(mockAnalyticsProvider.setAppId(appId)).toHaveBeenCalled;
        expect(mockAnalyticsProvider.setSaUsageEnviroment(enviroment)).toHaveBeenCalled;
    });
~~~~~
it('should assign appid and environment details to provider',
    function (done) {
        var appId = 9086;
        var enviroment = 'DEV';
        expect(mockAnalyticsProvider.setAppId(appId)).toHaveBeenCalled;
        expect(mockAnalyticsProvider.setSaUsageEnviroment(enviroment)).toHaveBeenCalled;
        done();
    });
```

**Comment by mmanela** [comment] 2016-12-12 21:49
Please give me a full repro that I can run locally

**Comment by dpmartin990** [comment] 2016-12-12 23:59
Shall I zip it up and email it to you?

**Comment by mmanela** [comment] 2016-12-13 16:52
Or just create a git repo

**Comment by dpmartin990** [comment] 2016-12-13 20:54
Ah, OK, of course.  Will get back to you on that.

**Comment by dpmartin990** [comment] 2016-12-14 23:08
I have removed a bunch of nonessentials to simplify and created a Repo named TestRepository.  You should have gotten an invite to it.

**Comment by mmanela** [comment] 2016-12-20 22:57
@dpmartin990 I took a look and the issue is in your specs ```toHaveBeenCalled``` is missing its parenthesis. You have it as ```toHaveBeenCalled``` instead of ```toHaveBeenCalled()```.

**Comment by dpmartin990** [comment] 2016-12-21 18:42
Ok since I extracted just a portion of the original to make this recreation of the problem, I will double-check my original as well to see if that is the issue there as well and get back to you.  Thanks for looking at it.

**Comment by mmanela** [comment] 2017-01-05 16:29
I am closing for now but reopen if issue persists

**Closed by mmanela** 2017-01-05 16:29 UTC
