### ISSUE TITLE
Use Qunit in project, not local

### ISSUE THREAD

**Issue by jt4000** [mmanela/chutzpah#621] opened 2017-03-27 13:23 UTC
Hello,
If I want to use the Qunit library from a VS solution project, and not the library at the local computer, is it possible to do it? 

The reason is to facilitate the change of the Qunit in relation to new version.

Thank you!

**Comment by mmanela** [comment] 2017-03-27 16:54
Dupe of #583

**Closed by mmanela** 2017-03-27 16:54 UTC
