### ISSUE TITLE
IO error when saving a file in VS

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#482] opened 2016-03-04 21:58 UTC
This is the error I'm getting when saving a test file in VS:
I think the root cause of this error is that I declared a variable and didn't initialize it in beforeEach or in the test itself, the following should not happen in any case I think...
```
------ Discover test started ------
Error: System.IO.IOException: The process cannot access the file 'd:\github\israelhikingmap\site\tests\israelhiking.web.tests\services\parsers\_Chutzpah.e1712fc1809376cb7b9206b8007636fe.test.html' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Chutzpah.Wrappers.FileSystemWrapper.Save(String path, String contents)
   at Chutzpah.TestHarnessBuilder.CreateTestHarness(TestContext testContext, TestOptions options)
   at Chutzpah.TestRunner.<>c__DisplayClass15.<ExecuteTestContexts>b__14(TestContext testContext)
While Running:d:\github\israelhikingmap\site\tests\israelhiking.web.tests\services\parsers\geojsonparsertests.ts

Error: Error opening d:/github/israelhikingmap/site/tests/israelhiking.web.tests/services/parsers/_Chutzpah.e1712fc1809376cb7b9206b8007636fe.test.html: No such file or directory
While Running:d:\github\israelhikingmap\site\tests\israelhiking.web.tests\services\parsers\geojsonparsertests.ts

Error: Unknown error occurred when executing test file. Received exit code of 2
While Running:d:\github\israelhikingmap\site\tests\israelhiking.web.tests\services\parsers\geojsonparsertests.ts

========== Discover test finished: 0 found (0:00:01.5739419) ==========
```

the following is the test that causes this:
```js
/// <reference path="../../../../isrealhiking.web/scripts/typings/geojson/geojson.d.ts" />
/// <reference path="../../../../isrealhiking.web/services/parsers/iparser.ts" />
/// <reference path="../../../../isrealhiking.web/services/parsers/baseparser.ts" />
/// <reference path="../../../../isrealhiking.web/services/parsers/geojsonparser.ts" />

module IsraelHiking.Tests {
    describe("GeoJson Parser", () => {

        var geoJsonParser: Services.Parsers.GeoJsonParser;

        //beforeEach(() => {
        //    geoJsonParser = new Services.Parsers.GeoJsonParser();
        //});

        it("Parse geoJson string", () => {
            expect(2).toBe(2);
        });
    });
}
```

uncommenting the before each makes this error disappear.

**Comment by HarelM** [comment] 2016-03-04 22:03
No, I stand corrected, this has nothing to do with the comment in and out...

**Comment by mmanela** [comment] 2016-03-12 16:27
Interesting. What version of VS (like 2015 update 1?) and do you have any extensions installed besides chutzpah?

**Comment by HarelM** [comment] 2016-03-12 18:50
VS 2015 community update 1 with Resharper 10.2 and VSCommands. web essentials 2015.1, opencover UI, Grunt launcher,Glyphfriend, Github extension.

**Comment by mmanela** [comment] 2016-03-12 22:26
Does it repro if you disable resharper?

**Comment by HarelM** [comment] 2016-03-13 21:34
Yes, just verified it.
I think it might have to do with trying to discover tests when a beforeEach fails, but I'm not sure.
In any case I think you can use my repository to reproduce:
comment out the line ```angular.mock.module("LocalStorageModule");``` in ```HashServiceTests.ts``` and save the file, it reproduces when I try it.
http://www.github.com/israelhikingmap/site

**Comment by mmanela** [comment] 2016-03-21 13:47
Closing this one as a dupe of #489

**Closed by mmanela** 2016-03-21 13:47 UTC
