### ISSUE TITLE
Encountered a deceleration exception

### ISSUE THREAD

**Issue by HarelM** [mmanela/chutzpah#420] opened 2015-10-17 20:00 UTC
I have the "describe" (jasmin's test class) in the VS test window saying a deceleration exception has occurred: Can't find variable angular.

The tested worked not long ago before I moved and renamed some files but I don't understand what I need to do.

Test code can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web.Tests/services/MicrosoftElevationProviderTests.ts

the whole project is two folders up:
https://github.com/IsraelHikingMap/Site/tree/master/IsraelHiking.Web.Tests

If you have some time to take a look at it I'd appreciate it as I can't understand what I need to do in order to make the tests run. I know that the problem is with the beforeEach method and the angular variable but it looks like I configured everything as it should be...

**Comment by mmanela** [comment] 2015-10-19 13:18
I will take a look when I get some time but at first glance once recommendation is to use the chutzpah.json file to manage your references instead of refefences comments. This just makes it easier to manage the set of references especially when you do file moves/ renames.

**Comment by HarelM** [comment] 2015-10-19 14:30
Every time I try to use this file for references the test discovery fails and I can't run my tests...

**Comment by mmanela** [comment] 2015-10-19 15:28
Sounds like a misconfiguration issue. If you can build a sample using it I can take a look at that too

**Comment by HarelM** [comment] 2015-10-19 18:36
I can't reproduce, weird... I have moved the reference to the json file, no luck yet...

**Comment by mmanela** [comment] 2015-10-20 04:18
You can't reproduce the original issue?

**Comment by HarelM** [comment] 2015-10-20 05:07
No, just the fact that the test discovery fails, still can't run the tests.

**Comment by mmanela** [comment] 2015-10-30 13:36
I am confused. What issue are you hitting and do you have a minimal repro I can use?

**Comment by HarelM** [comment] 2015-10-30 13:48
The error I'm getting is "Encountered a deceleration exception".
Which does not allow me to run the tests.
I'll see if I can manage to create a small project that has the same error.
If you don't want to wait for me you can "get" the above repository and see if you can make the MicrosoftElevationProviderTests.ts test run.
basically it uses angular's $http service.

**Comment by HarelM** [comment] 2015-10-30 23:50
Here are the steps to reproduce, This is minimal although might look like a lot:
Using visual studio 2015 community edition with typescript 1.6.3 (I'm guessing other version of VS will reproduce this too, type script latest version due to new lodash declerations).
Create a project of type typescript html application.
Using Nuget add reference to: Angular.Core, Angular definitely typed, jasmine definitely typed.
Change the content of app.ts to
```js
namespace App {
    export class Requester {
        private $http: angular.IHttpService;

        constructor($http: angular.IHttpService) {
            this.$http = $http;
        }

        public doSomething(a: string[]): angular.IHttpPromise<string> {
            return this.$http.get("http://www.google.com").success((reposne: string) => {
                a.push(reposne);
            });
        }
    }
}
```
create a type script file called Tests.ts with the following content:
```js
namespace Tests {
    describe("tests", () => {
        let unit: App.Requester;

        beforeEach(angular.mock.inject((_$http_: angular.IHttpService, _$httpBackend_: angular.IHttpBackendService) => {
            unit = new App.Requester(null);
        }));
        it("should run", () => {
            expect(1).toBe(1);
        });
    });
}
```
Add chutzpah.json file with the following content:
```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    {
      "Includes": ["*\\scripts\\angular.js","*\\scripts\\angular-mocks.js", "*\\app.js"]
    }
  ],
  "Tests": [
    { "Include": "*\\*tests.ts" }
  ]
}
```
See Error message in test window.
When commenting out the ```beforeEach``` the test runs and pasts.
Let me know if there's any thing else I can do in order to help.

**Comment by HarelM** [comment] 2015-10-31 00:42
The horror... just spent a few hours on this...
This is the final content of the Reference in the chutzpah.json file which made the test work.
```
 "References": [
    { "Path": "Scripts/angular.js" },
    { "Path": "Scripts/angular-mocks.js" },
    { "Includes": [ "*\\app.ts"] }
  ],
```
This is what I said about the framework feels shaky - There should not be any difference if I write the first json reference or the second...

**Comment by HarelM** [comment] 2015-10-31 23:42
While the above worked for code and tests that are in the same project, I can't figure out how to make it work while the tests are in one project and the production code it in another project.
all my attempts for relative path manipulation failed (using ```../``` multiple times etc...).
I have updated the my Github with the above changes that resolve angular.mock.inject issue, but it still doesn't find my ts file that is in the other project, thought are welcome.

**Comment by HarelM** [comment] 2015-11-01 12:46
Is there a way for me to debug this? maybe compile the project? Run from command line? check some sort of output to see why the references are not present? anything? I really like VS and I'd love not to run tests from command line...

**Comment by HarelM** [comment] 2015-11-01 20:43
I think I found the root of all evil. well not really, but I think I'm on to a bug:
I have downloaded the console runner hoping I'll have more logs, which was a thought in the right direction :-)
From the log file it emits here are the relevant line:
```
chutzpah.console.exe Information: 0 : Time:22:26:23.0680290; Thread:1; Message:Investigating reference file path '../../isrealhiking.web/services/elevation/MicrosoftElevationProvider.ts'
chutzpah.console.exe Information: 0 : Time:22:26:23.0700293; Thread:1; Message:Added file 'C:\Develop\GitHub\IsraelHikingMapSite\isrealhiking.web\services\elevation\MicrosoftElevationProvider.ts' to referenced files. Local: True, IncludeInTestHarness: True
chutzpah.console.exe Information: 0 : Time:22:26:23.0710295; Thread:1; Message:Processing referenced file 'C:\Develop\GitHub\IsraelHikingMapSite\isrealhiking.web\services\elevation\MicrosoftElevationProvider.ts' for expanded references
```
so far so good I think, but then come these lines:
```
chutzpah.console.exe Warning: 0 : Time:22:26:23.1170323; Thread:1; Message:Can't find location for generated path on C:\Develop\GitHub\IsraelHikingMapSite\isrealhiking.web\services\elevation\MicrosoftElevationProvider.ts since it is not inside of configured source dir C:\Develop\GitHub\IsraelHikingMapSite\Tests\IsraelHiking.Web.Tests
chutzpah.console.exe Error: 0 : Time:22:26:23.1230318; Thread:1; Message:Chutzpah determined generated .js files are missing but the compile mode is External so Chutzpah can't compile them. Test results may be wrong.
```
Which is correct, the MicrosoftElevationProvider.js file is in isrealhiking.web\services\elevation folder and not in the test project.

the following is the chuztpah.json file:
```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ]
  },
  "References": [
    { "Path": "../../isrealhiking.web/scripts/angular.js" },
    { "Path": "../../isrealhiking.web/scripts/angular-mocks.js" },
    { "Path": "../../isrealhiking.web/scripts/leaflet-0.7.3.js" },
    { "Path": "../../isrealhiking.web/scripts/angular-toastr.js" },
    { "Path": "../../isrealhiking.web/services/elevation/MicrosoftElevationProvider.ts" },
    { "Path": "../../isrealhiking.web/common/israelhikingdata.ts" }
  ],
  "Tests": [
    { "Include": "*\\**\\*Tests.ts" }
  ]
}
```
I can change the ts to js and the test will run but this is a workaround and not a real solution.
Do you want me to open another issue on that? because this issue is not related to the above scenario. the above scenario is caused by the fact that the framework did not find angular-mocks.js in the beaforeEach method...

**Comment by mmanela** [comment] 2015-11-01 23:47
I think for the (compile setting)[https://github.com/mmanela/chutzpah/wiki/Compile-Setting] you need to configure the SourceDirectory to be the root folder that encompasses both the source and test projects. By default I believe SourceDirectory will be the folder the chutzpah.json is in which will not include your source files. Your other option is to put chutzpah.json at the root of your project.

**Comment by HarelM** [comment] 2015-11-02 13:47
I'll try it tonight, Thanks.
I would recommend a wiki page about how to include angular.js with chutzpah since it requires some tweaking - since angular needs to be included first and no more than once.
Also when doing code coverage it collides with blanket.js when using angular.js file and not angular.min.js file.
I would also recommend a troubleshooting wiki page (what should one do if the tests fail/are not present in the test explorer window) - when I ran from command line and looked at the logs/generated html file I was able to understand what's wrong a lot faster and could fix it myself without your help.
This way once someone has an issue like I did you could first and foremost send him to read these pages and ask him to post the relevant log files which could have made this thread a lot shorter... :-)

**Comment by mmanela** [comment] 2015-11-02 15:09
There is some content here: https://github.com/mmanela/chutzpah/wiki/Debugging-Unit-Tests  But I will add more to it about tracing

**Comment by HarelM** [comment] 2015-11-02 20:40
Can I use relative path for sourceDirectory? it doesn't look like putting ../../ or ..\\..\\ does anything...

**Comment by mmanela** [comment] 2015-11-02 22:48
Using relative paths should work. The code looks right to me but I would need to see the whole context I guess.

**Comment by HarelM** [comment] 2015-11-02 22:59
Didn't work for me. I decided to move the json file to the root...
Do you need anything for me in order to reproduce it?

**Comment by mmanela** [comment] 2015-11-02 23:02
I will validate the relative source directory setting. If it works for me I
will ask for more info

**Comment by mmanela** [comment] 2015-12-19 14:37
The relative source directory seems to work fine for me so I would need more details and a working example.

**Comment by HarelM** [comment] 2015-12-26 20:52
This is more than a month and a half old... you can't really expect me to have a non working example.
I solved the issue above by placing the json at the root directory of the two projects (test and production).
The following is the commit I made to move the file:
https://github.com/IsraelHikingMap/Site/commit/da84e6d9acbbb014a6f3b3fa6b9ba080d183fcf0
I'm not sure I checked-in non working code but before this commit you'd have an example of tests and production in separate folders, if you can make it work without moving the json file let me know.

**Comment by mmanela** [comment] 2015-12-28 23:11
I have confirmed that relative paths *do* work correctly for SourceDir and OutDir settings (although I will be renaming those settings soon).  So that leave me not having a repro for you. If you are still interested in having this solved please provide me with a minimal repro of your issue. Otherwise we can close this out.

**Comment by HarelM** [comment] 2015-12-28 23:26
I currently do not have the time create a small repo, maybe later this week.
Please try, if you can, to create a folder with tests, a folder with code and that the code is using angularJS and the tests are using angularJS mocks and jasmine in the beforeEach method.
I couldn't make the above scenario work no matter what I tried when the chutpah.json file was inside the tests folder.

**Comment by HarelM** [comment] 2016-01-01 15:03
[ChutzpahExample.zip](https://github.com/mmanela/chutzpah/files/75934/ChutzpahExample.zip)
I hope this will shed some light on the problem I'm facing.
I have added some comments to the chutzpah json file to explain what works for me and what doesn't.
There are about three issues in this file. 
please let me know if I did something wrong or that these are bugs.

**Comment by mmanela** [comment] 2016-01-01 23:25
Thanks a lot.  I will take a look and get back to you. I appreciate you taking the time to build this.

**Comment by mmanela** [comment] 2016-01-18 01:41
@HarelM  Thank so much for the sample project. I can now understand what the confusion was and I have a solution. The following Chutzpah.json file works (but is not at all obvious):

```
{
  "Framework": "jasmine",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true,
    "SourceDirectory": "../../",
    "OutDirectory": "../../"
  },
  "References": [
    { "Path": "../../ChutzpahExample/Scripts/angular.min.js" },
    { "Path": "../../ChutzpahExample/Scripts/angular-mocks.js" },
    { "Path": "../../ChutzpahExample/Example", "Includes": [ "*.ts" ] }
  ],
  "Tests": [{ "Include": "*Tests.ts" }]
}
```

When you leave off Source/OutDirectory settings chutzpah assumes them both to be the location of the chutzpah.json file (which in this case is in your test folder). This won't work for you since the source files are in a another tree. You correctly tried to use SourceDirectory setting but by setting only that it was telling Chutzpah that your paths in SourceDirectory compile to the default OutDirectory which is the location of your Chutzpah.json file. By setting BOTH source and out directories you let Chutzpah know to map both source/compiled paths correctly.

I realize this is less than obvious so would love thoughts/feedback on ways to make this clearer.

**Comment by mmanela** [comment] 2016-02-01 21:42
@HarelM Ping

**Comment by HarelM** [comment] 2016-02-01 23:01
As you can see from your example above there are too many places where you add the ```"../../"```.
Thinking out load here (brain storming if you will) - 
 * Since Visual Studio is compiling the ts to js files in the same folder I would go and assume that the out directory is the same as the source directory unless told otherwise.
 * Also I'm not sure why you need both source directory and out directory - but I'm probably not seeing the big picture.
 * I would expect the following to work: ```Reference: [ { Path: "../../ChutpahExample/Scripts", Includes: ["angular.min.js, angular.mocks.min.js"]``` - note that the order is important here, also skipping the ```../../``` would be nice if it is defined in the source/out directory.
 * Test discovery and test run are the only places you can interact with the developer - use the output windows to let the user know what was found where and in what order. if a line in the chutzpah file does not result in any matches the user should know about it - kind of like warning when compiling. otherwise he's blind (and gets frustrated)...
 * Another option is to split the references to folders and files: ```ReferencesFolders: ["folder1", "folder2"], ReferencesFiles: ["file1.js", "file2.js", "*.ts"]``` but I'm not sure this is ideal... 
 * When a test fail maybe you can add a link to the html file that ran the test so the developer could debug it using a browser? this way if there's something missing he'll be able to see it right away and not need to use the console runner?

I don't have anything else at the moment, sorry for the late response.

**Comment by mmanela** [comment] 2016-11-28 17:56
You no longer need both source and outdirectory as I showed above. It will assume a smarted default and work better.

**Closed by mmanela** 2016-11-28 17:56 UTC

**Comment by HarelM** [comment] 2016-11-28 22:17
I hope some of the ideas above are implemented :-) Keep up the good work.
